const packages = [
 {name:'Ana sponsor',tag:'Festivalin merkezinde',className:'main-sponsor',size:'16 m²',tickets:'40',description:'Festivalin hikâyesini markanızla birlikte yazalım.',features:['Şenliğe isim verme hakkı','Ana sahne ve iletişim materyallerinde logo','16 m² stant ve 12 sponsor bayrağı','Radyo TEDÜ röportajı ve reklam hakkı'],more:'Totem görünürlüğü, sosyal medya ve üniversite ekranlarında tanıtım, teşekkür plaketi ve 40 davetiye.'},
 {name:'Altın sponsor',tag:'Sahnenin enerjisine ortak ol',className:'gold-sponsor',size:'8 m²',tickets:'20',description:'Müziğin buluşturduğu yerde markanız da olsun.',features:['Konser sahnesine isim verme hakkı','Sahne, afiş ve programlarda logo','8 m² stant ve 6 sponsor bayrağı','Üniversite ekranlarında tanıtım'],more:'Etkinlik medya haberlerinde sponsor adı, teşekkür plaketi ve 20 davetiye.'},
 {name:'Gümüş sponsor',tag:'Birlikte daha görünür',className:'silver-sponsor',size:'8 m²',tickets:'10',description:'Kampüsün heyecanıyla doğrudan bağ kurun.',features:['Etkinlik materyallerinde logo','8 m² stant ve 4 sponsor bayrağı','Etkinlik kitapçığında tam sayfa reklam','Üniversite ekranlarında tanıtım'],more:'Etkinlik medya haberlerinde sponsor adı, teşekkür plaketi ve 10 davetiye.'},
 {name:'Stant sponsorluğu',tag:'Tanışalım, deneyelim, paylaşalım',className:'stand-sponsor',size:'Özel',tickets:null,description:'Ürünlerinizi festivalin içinde deneyime dönüştürün.',features:['Markanıza uygun stant alanı','Stant kurulumu ve teknik destek','Yiyecek, içecek veya ürün satışı','Alan büyüklüğüne göre teklif'],more:'Stant konumu, ölçüsü ve kullanım koşulları organizasyon ekibiyle birlikte netleştirilir.'}
];
document.querySelector('#content').innerHTML = `
<section id="festival" class="about wrap section"><div><span class="section-label">Kampüsün en iyi hâli</span><h2>Bir festivalden<br>çok daha fazlası.</h2></div><div class="about-copy"><p>Konserin ilk notasında, tasarım pazarında yeni bir keşifte, hiç tanımadığın biriyle aynı şarkıyı söylerken. TEDÜ Fest, Ankara'nın kalbinde kampüs hayatını sokağın enerjisiyle buluşturuyor.</p><p>Öğrenci topluluklarından açık hava konserlerine, gün boyunca keşfedecek; akşam olduğunda birlikte hatırlayacak çok şey var.</p><div class="facts"><div><strong>10+ yıl</strong><span>etkinlik geleneği</span></div><div><strong>Birlikte</strong><span>öğrenci topluluklarıyla</span></div><div><strong>Keşfet</strong><span>kampüsün ritmini</span></div></div></div></section>
<section id="program" class="program section"><div class="wrap"><div class="section-heading"><div><span class="section-label">Gündüzden geceye</span><h2>Senin festivalin,<br>senin ritmin.</h2></div><p>Biraz müzik, biraz keşif, bolca birlikte olmak.<br>Festivalin farklı yüzleriyle tanış.</p></div><div class="program-layout"><div class="program-menu" role="tablist" aria-label="Festival etkinlikleri"></div><div id="program-panel" class="program-panel" role="tabpanel" tabindex="0"></div></div></div></section>
<section id="sponsorluk" class="sponsorship section wrap"><div class="section-heading"><div><span class="section-label">Bu enerjinin bir parçası ol</span><h2>İyi şeyler,<br>birlikte olur.</h2></div><div class="section-intro"><p>Markanıza uygun katılımı seçin.<br>Festivalde birlikte neler yapabileceğimizi konuşalım.</p><a class="text-link" href="assets/TEDU-Fest-Sponsorluk-2024.pdf" download>Sponsorluk dosyasını indir</a></div></div><div class="sponsor-grid">${packages.map((p,i)=>`<article class="sponsor-card ${p.className}"><div class="package-top"><span>${p.tag}</span><span aria-hidden="true">${['✳','✹','✦','✚'][i]}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="package-facts"><span><b>${p.size}</b> stant alanı</span>${p.tickets?`<span><b>${p.tickets}</b> davetiye</span>`:'<span><b>Size özel</b> teklif</span>'}</div><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><details><summary>Tüm sponsorluk hakları</summary><p>${p.more}</p></details><a class="button package-button" data-package="${p.name}" href="mailto:sca@tedu.edu.tr">${i===3?'Stant için görüşelim':'Teklif iste'}</a></article>`).join('')}</div></section>

`;

const activities = [
 {title:'Topluluklarla tanış',label:'Topluluklar & birlikler',photo:'crowd',alt:'TEDÜ etkinliğinde bir araya gelen katılımcılar',text:'Yeni insanlarla tanış, ilgi alanını bul. Öğrenci toplulukları ve birlikleri kampüsün ortak enerjisini festival alanına taşıyor.',tags:['Topluluk stantları','Kampüs kültürü','Yeni karşılaşmalar']},
 {title:'Keşfe küçük bir mola',label:'Tasarım pazarı & Gastro Fest',photo:'market',alt:'TEDÜ tasarım pazarındaki el yapımı ürünler ve katılımcılar',text:'El emeği tasarımların, yeni tatların ve yaratıcı fikirlerin arasında dolaş. Festivalin en renkli buluşma noktalarını keşfet.',tags:['Tasarım pazarı','Gastro Fest','Yaratıcı üretim']},
 {title:'Oyuna sen de katıl',label:'Oyunlar & aktiviteler',photo:'crowd',alt:'Bir kampüs etkinliğinde bir araya gelen TEDÜ öğrencileri',text:'Bir takım kur, yeni bir şey dene, günün akışına katıl. Kampüs, oyunlar ve birlikte geçirilen anlarla hareketleniyor.',tags:['Birlikte oyun','Kampüs aktiviteleri','Yeni deneyimler']},
 {title:'Her insan bir hikâye',label:'Yaşayan kütüphane',photo:'market',alt:'TEDÜ kampüsünde bir etkinlikten arşiv fotoğrafı',text:'Dinlemeye, paylaşmaya ve farklı hikâyelerle tanışmaya alan aç. Yaşayan kütüphane, festivalin içten sohbetlere ayrılan durağı.',tags:['Sohbet','Hikâyeler','Farklı bakışlar']},
 {title:'Aynı şarkıda buluşalım',label:'Açık hava konserleri',photo:'festival',alt:'TEDÜ Fest açık hava konseri ve sahne ışıkları',text:'Günün sonu, gecenin başlangıcı. Işıklar yandığında kampüsün ritmi yükselir; sevdiğin şarkılar hep bir ağızdan söylenir.',tags:['Açık hava','Canlı müzik','Birlikte söyle']}
];
const tabs=document.querySelector('.program-menu');
tabs.innerHTML=activities.map((a,i)=>`<button type="button" role="tab" id="activity-${i}" aria-controls="program-panel" aria-selected="${i===4}" tabindex="${i===4?0:-1}" data-activity="${i}"><strong>${a.label}</strong><b aria-hidden="true">${i===4?'♫':'✳'}</b></button>`).join('');
function showActivity(i,focus=false){const a=activities[i];tabs.querySelectorAll('button').forEach((b,n)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1;if(n===i&&focus)b.focus()});const panel=document.querySelector('#program-panel');panel.setAttribute('aria-labelledby','activity-'+i);panel.innerHTML=`<img src="assets/${a.photo}.jpg" alt="${a.alt}" loading="lazy"><div class="program-text"><span>${a.label}</span><h3>${a.title}</h3><p>${a.text}</p><div class="program-tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div></div>`;}
tabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b)showActivity(Number(b.dataset.activity))});
tabs.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const current=Number(document.activeElement.dataset.activity);const next=e.key==='Home'?0:e.key==='End'?4:(current+(['ArrowDown','ArrowRight'].includes(e.key)?1:4))%5;showActivity(next,true)});showActivity(4);
