(() => {
 const sections = {
  naming:{title:'Üst branda & isim hakkı',short:'Branda & isim hakkı',label:'Sahnenin imzası',package:'Altın sponsor',area:'Sahne brandası ve isim hakkı',description:'Festivalin buluşma noktasına markanızın adını verin. Sahne üstü branda, festival kimliğiyle markanızı aynı çerçevede buluşturur.',features:['Konser sahnesine isim verme hakkı','Sahne üstü branda giydirme','Sahne iletişiminde marka görünürlüğü'],color:'#9e59e8'},
  led:{title:'Ana LED ekran',short:'Ana LED ekran',label:'Büyük ekranda büyük etki',package:'Özel iş birliği',area:'Ana sahne LED ekranı',description:'Konser aralarında videolarınız, görselleriniz ve kampanya mesajlarınız sahnenin büyük ekranında yer alsın.',features:['Markaya özel video ve animasyon','Konser arası görsel gösterimler','İçerik ve yayın akışının birlikte planlanması'],color:'#f163b4'},
  wings:{title:'Yan marka panoları',short:'Yan panolar',label:'Sahnenin iki yanında',package:'Özel iş birliği',area:'Sahne yan marka panoları',description:'Sahnenin iki yanındaki panolarda markanızı görünür kılın. Logo ve kampanya görselleriniz konser boyunca sahneyle birlikte kadrajda kalsın.',features:['Sağ ve sol marka yüzeyleri','Logo ve kampanya görseli kullanımı','Sahne tasarımıyla bütünleşen uygulama'],color:'#46a9cf'},
  front:{title:'Sahne önü giydirme',short:'Sahne önü',label:'En öndeki karşılaşma',package:'Özel iş birliği',area:'Sahne önü giydirme',description:'Sahne platformunun ön yüzünü markanızın hikâyesine ayırın. Katılımcıya yakın, geniş ve kesintisiz bir görünürlük alanı oluşturun.',features:['Platform önünde marka giydirme','Geniş yatay tasarım alanı','Markanıza özel görsel uygulama'],color:'#ff975b'}
 };
 const truss = (x,y,w,h) => `<g stroke="#a4a0b1" stroke-width="3" fill="none"><rect x="${x}" y="${y}" width="${w}" height="${h}"/>${Array.from({length:Math.floor(h/38)},(_,i)=>`<path d="M${x} ${y+i*38}l${w} 38m-${w} 0l${w} -38"/>`).join('')}</g>`;
 const speakers = x => `<g><rect x="${x}" y="276" width="49" height="227" rx="6" fill="#292534" stroke="#4c445f"/>${[307,360,413,466].map(y=>`<circle cx="${x+24.5}" cy="${y}" r="19" fill="#16131d" stroke="#4e475d" stroke-width="2"/><circle cx="${x+24.5}" cy="${y}" r="7" fill="#393142"/>`).join('')}</g>`;
 const hotspotAttrs=(id,label)=>`class="stage-zone" data-stage-zone="${id}" tabindex="0" role="button" aria-label="${label}" aria-pressed="${id==='naming'}"`;
 const html=`<section id="sahne-sponsorlugu" class="stage-sponsors section"><div class="wrap"><div class="section-heading"><div><span class="section-label">Sahne sponsorluğu</span><h2>Sahneye adını yaz.<br>Herkes görsün.</h2></div><p>Sahnenin üzerindeki bir yüzeyi seç.<br>Markanın nerede, nasıl görüneceğini keşfet.</p></div>
 <div class="stage-explorer"><div class="stage-bar"><span><b>TEDÜ Fest</b> / Sahne görünürlüğü</span><span>Üzerine gel veya tıkla</span></div><div class="stage-frame" id="stage-frame">
 <svg class="stage-elevation" viewBox="0 0 1200 690" xmlns="http://www.w3.org/2000/svg" aria-label="TEDÜ Fest sahnesinin önden görünümü ve seçilebilir sponsorluk yüzeyleri">
 <defs><linearGradient id="stage-sky" x2="0" y2="1"><stop stop-color="#f0eafb"/><stop offset="1" stop-color="#fbf8fc"/></linearGradient><linearGradient id="stage-roof" x2="0" y2="1"><stop stop-color="#777181"/><stop offset="1" stop-color="#332b43"/></linearGradient><linearGradient id="stage-led" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#391161"/><stop offset=".5" stop-color="#8533bf"/><stop offset="1" stop-color="#db5aa0"/></linearGradient><linearGradient id="stage-beam" x2="0" y2="1"><stop stop-color="#ffffff" stop-opacity=".3"/><stop offset="1" stop-color="#ffffff" stop-opacity="0"/></linearGradient><pattern id="led-grid" width="13" height="13" patternUnits="userSpaceOnUse"><rect x="1" y="1" width="2" height="2" fill="white" opacity=".12"/></pattern></defs>
 <rect width="1200" height="690" fill="url(#stage-sky)"/><ellipse cx="600" cy="629" rx="442" ry="29" fill="#b29fc4" opacity=".16"/><g fill="#be9bd8" opacity=".3"><circle cx="121" cy="141" r="2"/><circle cx="187" cy="83" r="3"/><circle cx="1042" cy="122" r="3"/><circle cx="1110" cy="241" r="2"/><circle cx="130" cy="477" r="2"/></g>
 ${truss(255,190,26,368)}${truss(919,190,26,368)}
 <g stroke="#aaa4b5" stroke-width="3" fill="none"><path d="M270 193H935M270 226H935"/>${Array.from({length:14},(_,i)=>`<path d="M${270+i*47} 193l47 33m-47 0 47-33"/>`).join('')}</g>
 <path d="M224 186 348 142H852L976 186Z" fill="url(#stage-roof)"/><rect x="235" y="184" width="730" height="20" rx="2" fill="#464050"/>
 <g ${hotspotAttrs('naming','Üst branda ve isim hakkı alanını seç')}><rect class="zone-face" x="285" y="104" width="630" height="72" rx="5" fill="#faf7fe" stroke="#b995df" stroke-width="2"/><text x="600" y="143" text-anchor="middle" fill="#6123a2" font-family="Manrope,Arial,sans-serif" font-size="24" font-weight="800" letter-spacing="3">MARKAN İLE TEDÜ FEST</text><text x="600" y="161" text-anchor="middle" fill="#a082ba" font-family="Manrope,Arial,sans-serif" font-size="9" letter-spacing="2">ÜST BRANDA & İSİM HAKKI</text><circle class="stage-pin" cx="885" cy="119" r="6" fill="#a158e4"/></g>
 <rect x="284" y="231" width="632" height="327" rx="3" fill="#2e213b"/>
 <g ${hotspotAttrs('led','Ana LED ekran alanını seç')}><rect class="zone-face" x="292" y="238" width="616" height="311" fill="url(#stage-led)" stroke="#c47ceb" stroke-width="2"/><rect x="292" y="238" width="616" height="311" fill="url(#led-grid)"/><g fill="none" stroke="#f38ad8" opacity=".2">${[130,170,210,250].map(r=>`<ellipse cx="600" cy="390" rx="${r}" ry="${r*.65}"/>`).join('')}</g><image href="assets/logos/tedu-fest-color.svg" x="465" y="256" width="270" height="207"/><text x="600" y="488" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="16" font-weight="700" fill="#fff4ff" letter-spacing="3">BU ENERJİDE MARKAN DA VAR.</text><text x="600" y="522" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="10" fill="#e6c3fa" letter-spacing="2">ANA LED EKRAN</text><circle class="stage-pin" cx="887" cy="257" r="6" fill="#ff9fda"/></g>
 ${speakers(226)}${speakers(925)}
 <g class="stage-beams" pointer-events="none">${[337,445,553,661,769,877].map((x,i)=>`<path d="M${x} 222  ${x-70+i*4} 544 ${x+82-i*6} 544Z" fill="url(#stage-beam)"/><rect x="${x-9}" y="204" width="18" height="18" rx="4" fill="#2a2434"/><ellipse cx="${x}" cy="224" rx="7" ry="3" fill="${i%2?'#ffb4e7':'#fff5b5'}"/>`).join('')}</g>
 <g stroke="#8c899c" stroke-width="5"><path d="M164 431V562M1036 431V562"/></g>
 <g ${hotspotAttrs('wings','Sol yan marka panosu alanını seç')}><rect class="zone-face" x="104" y="340" width="124" height="104" rx="4" fill="#dcecf5" stroke="#79b0c8" stroke-width="2"/><text x="166" y="383" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="800" fill="#426780">MARKAN</text><text x="166" y="403" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="800" fill="#426780">BURADA</text><text x="166" y="429" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="8" fill="#6890a8">SOL YAN PANO</text><circle class="stage-pin" cx="215" cy="353" r="5" fill="#439dc3"/></g>
 <g ${hotspotAttrs('wings','Sağ yan marka panosu alanını seç')}><rect class="zone-face" x="972" y="340" width="124" height="104" rx="4" fill="#dcecf5" stroke="#79b0c8" stroke-width="2"/><text x="1034" y="383" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="800" fill="#426780">MARKAN</text><text x="1034" y="403" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="12" font-weight="800" fill="#426780">BURADA</text><text x="1034" y="429" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="8" fill="#6890a8">SAĞ YAN PANO</text><circle class="stage-pin" cx="1083" cy="353" r="5" fill="#439dc3"/></g>
 <path d="M245 546H955L982 565H218Z" fill="#686071"/><rect x="218" y="564" width="764" height="56" fill="#30243e"/>
 <g ${hotspotAttrs('front','Sahne önü giydirme alanını seç')}><rect class="zone-face" x="231" y="571" width="738" height="42" fill="#f7cfb9" stroke="#ef996c" stroke-width="2"/><text x="600" y="598" text-anchor="middle" font-family="Manrope,Arial,sans-serif" font-size="17" font-weight="800" fill="#934b3c" letter-spacing="5">MARKAN BURADA</text><circle class="stage-pin" cx="951" cy="584" r="5" fill="#ed8953"/></g>
 <g fill="#51415f"><rect x="544" y="620" width="112" height="9"/><rect x="530" y="629" width="140" height="9"/><rect x="516" y="638" width="168" height="9"/></g>
 </svg>
 <div id="stage-popover" class="stage-popover" hidden><div><span id="stage-popover-label"></span><button type="button" aria-label="Sahne açıklamasını kapat" id="stage-close">×</button></div><h3 id="stage-popover-title"></h3><p id="stage-popover-description"></p><a href="mailto:sca@tedu.edu.tr" class="stage-popover-cta">Bu yüzey için görüşelim</a></div>
 </div><div class="stage-zone-tabs" role="group" aria-label="Sahne üzerindeki sponsorluk alanları">${Object.entries(sections).map(([id,s])=>`<button type="button" data-stage-select="${id}" aria-pressed="${id==='naming'}"><i style="background:${s.color}"></i>${s.short}</button>`).join('')}</div>
 <div class="stage-selection" aria-live="polite"><div class="stage-selection-copy"><span id="stage-detail-label"></span><h3 id="stage-detail-title"></h3><p id="stage-detail-description"></p><ul id="stage-detail-features"></ul></div><div class="stage-selection-action"><span>İlgili sponsorluk</span><strong id="stage-detail-package"></strong><a id="stage-contact" href="mailto:sca@tedu.edu.tr" class="button">Sahne için teklif iste</a></div></div></div>
 </div></section>`;
 document.querySelector('#content').insertAdjacentHTML('beforeend',html);
 let pinned=false;
 const frame=document.querySelector('#stage-frame'),popover=document.querySelector('#stage-popover');
 const setText=(id,text)=>document.getElementById(id).textContent=text;
 function select(id,showPopover=false){const s=sections[id];
  document.querySelectorAll('[data-stage-zone],[data-stage-select]').forEach(el=>{el.setAttribute('aria-pressed',String((el.dataset.stageZone||el.dataset.stageSelect)===id));});
  setText('stage-detail-label',s.label);setText('stage-detail-title',s.title);setText('stage-detail-description',s.description);setText('stage-detail-package',s.package);
  document.querySelector('#stage-detail-features').innerHTML=s.features.map(x=>`<li>${x}</li>`).join('');
  setText('stage-popover-label',s.label);setText('stage-popover-title',s.title);setText('stage-popover-description',s.description);
  popover.dataset.position=id==='wings'?'center':'right';popover.hidden=!showPopover;
 }
 document.querySelectorAll('[data-stage-zone]').forEach(el=>{
  el.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&!pinned)select(el.dataset.stageZone,true)});
  el.addEventListener('focus',()=>{if(!pinned)select(el.dataset.stageZone,true)});
  el.addEventListener('click',()=>{pinned=true;select(el.dataset.stageZone,true)});
  el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pinned=true;select(el.dataset.stageZone,true)}else if(e.key==='Escape'){pinned=false;popover.hidden=true;}});
 });
 document.querySelectorAll('[data-stage-select]').forEach(el=>el.addEventListener('click',()=>{pinned=false;select(el.dataset.stageSelect,false)}));
 frame.addEventListener('pointerleave',()=>{if(!pinned)popover.hidden=true});
 document.querySelector('#stage-close').addEventListener('click',()=>{pinned=false;popover.hidden=true});
 document.querySelector('#sahne-sponsorlugu').addEventListener('keydown',e=>{if(e.key==='Escape'){pinned=false;popover.hidden=true;}});
 select('naming');
})();
